# Base environment configuration
# Tuguldur T. Odbadrakh
# 10/13/2023

config:
  install_tree:
    root: ${FACSPACK_ENV}/opt
    projections:
      all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}
  template_dirs:
  - ${FACSPACK_CONF_HOST}/templates
  - ${FACSPACK_CONF_COMMON}/spack/templates
  - $spack/share/spack/templates
  build_stage:
  - /tmp/sauesw/spack-stage
  source_cache: ${FACSPACK_SOURCE_CACHE}
  extensions:
  - /sw/sources/facility-spack/defiant/share/spack/extensions/spack-olcf
  misc_cache: ${FACSPACK_ENV}/.mcache
  verify_ssl: true
  install_missing_compilers: false
  checksum: true
  dirty: false
  build_language: C
  build_jobs: 32
  ccache: false
  db_lock_timeout: 120
  package_lock_timeout: null
  shared_linking: rpath
  allow_sgid: true
  concretizer: 'clingo'
  locks: true
  suppress_gpg_warnings: false
  connect_timeout: 10
  test_stage: ~/.spack/test
  concretization: separately
  view: false

concretizer:
  unify: when_possible

mirrors:
  facility_builds: /sw/defiant/spack-env/mirrors/builds
  source_mirror: /sw/sources/facility-spack/source_mirror

repos:
- ${FACSPACK_CONF_COMMON}/spack/repos/olcf

